### ISSUE TITLE
Mega Issue: Deprovisioning Controls

### ISSUE THREAD

**Issue by njtran** [aws/karpenter-provider-aws#1738]
**Tell us about your request**
Karpenter provisions nodes and deprovisions nodes as described in the [docs](https://karpenter.sh/preview/concepts/deprovisioning/).

Some users are asking for more control on how to specify when Karpenter should disrupt nodes, and controls on how to rate-limit these disruptions. Opening this issue to aggregate the existing issues.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

** Karpenter disruption conditions:**
- [x] aws/karpenter#1716 - Karpenter should watch for AMI version updates and roll nodes to update to the new version.
- [x] aws/karpenter#1495 - allow specifying AMI Release version in Provisioner
- [x] aws/karpenter#1457 - Provisioner Drift
- [x] aws/karpenter#702 - Consume EC2 events similar to Node Termination Handler
- [x] aws/karpenter#1268 - Support for orphaned node destruction (both present in the cluster and outside)
- [x] aws/karpenter#1884 - Include `jitter` for TTLSecondsUntilExpired

**Control over how Karpenter should disrupt nodes:**
- [x] aws/karpenter#1018 - TTLSecondsUntilExpired can result in a lot of node churn at unexpected times. Rate-limit some termination decisions to reduce downtime.
- [x] aws/karpenter-core#753, aws/karpenter#903 - Time-based disruption controls
- [x] aws/karpenter-core#679 - Node Disruption Budget
- [ ] aws/karpenter-core#696 - Use a defined "expected cluster size" to drive deprovisioning
- [x] aws/karpenter-core#710 - Consider deprovisioning differently per-deprovisioning method?
- [x] aws/karpenter-core#735 - Per-node TTL for Consolidation
- [ ] kubernetes-sigs/karpenter#1030 - MinAge for NodeClaims

**Control over Karpenter's Eviction Policy:**
- [ ] aws/karpenter-core#752 - Allow specifying a non-permanent time frame `do-not-evict` for a pod, for un-programmatic removal use-cases. 
- [x] aws/karpenter#1532 - Include `allow-evict` annotation for pods for emptiness condition.
- [ ] aws/karpenter-core#701 - Don't evict running jobs
- [x] aws/karpenter#3052 - Max eviction tries
- [x] aws/karpenter-core#743 - Drain/Eviction Timeout

**Additional context**

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by vasylenko** [comment]
Heavy ➕ for https://github.com/aws/karpenter/issues/1716 - _Karpenter should watch for AMI version updates and roll nodes to update to the new version._

Use case: rotate (refresh) running instances when new security or other important update is released to the AMI used by the project/organization.

**Comment by prashil-g** [comment]
+1

**Comment by aavileli** [comment]
require something like the `max_number_of_node` to terminate when using `TTLSecondsUntilExpired`

**Comment by hajdukd** [comment]
Any update on this ? Pls

**Comment by blakepettersson** [comment]
Would it be possible to do something like a subset of #1841, which doesn't necessarily have to re-provision nodes? For example, updating instance tags shouldn't need to re-provision new nodes.

**Comment by hawkesn** [comment]
Another example of #1716 , I upgraded the EKS control plane and would like the nodes to upgrade their AMI accordingly.

**Comment by njtran** [comment]
Hey all. Check out https://github.com/aws/karpenter/pull/2569 for the design doc for node upgrades.

**Comment by karma-git** [comment]
@ellistarn Hi,

Maybe you could specify the ETA of NodeDrift implementation? 
Thank you

**Comment by ellistarn** [comment]
> Maybe you could specify the ETA of NodeDrift implementation?

We don't provide ETAs for features. I'd recommend keeping an eye on the repo and watching PRs if you're interested in tracking the progress.

**Comment by njtran** [comment]
Hey all, Node Drift for AMIs has been released in [v0.21.1](https://github.com/aws/karpenter/releases/tag/v0.21.0)! 

Read the docs about it [here](https://karpenter.sh/v0.21.0/concepts/deprovisioning/#drift) to enable AMI upgrade for nodes that are out-of-date with your current amiSelector in your AWSNodeTemplate. This [feature is disabled by default](https://karpenter.sh/v0.21.0/concepts/globalsettings/#feature-gates), so make sure to enable the featureGates.driftEnabled flag to get it working on your cluster!

We're working on extending node drift to respect other fields of the AWSNodeTemplate. More to come on that in the future!

**Comment by njtran** [comment]
Hey all, if you're tracking this, come give some feedback on https://github.com/aws/karpenter-core/pull/207!

This mentions some API improvements to then finish up Drift, and then tackle the remaining items left in this mega issue.

**Comment by ceastman-r7** [comment]
@njtran Do you have an example of how to set featureGates.driftEnabled flag if we are using helm to install karpenter?

**Comment by ceastman-r7** [comment]
Looks like this worked: 

--set settings.featureGates.driftEnabled=true

**Comment by Constantin07** [comment]
Hi All, slightly off topic - does anyone use AMI drift functionality in production ? or it's just supposed to be enabled and tested in development before rolled out to prod ? I'm looking for some best practices recommendations ...

**Comment by firebert521** [comment]
We have it in production right now and are watching it closely. Seems to
work well so far.

**Comment by njtran** [comment]
Hey all following this thread, looking for some data here! Are there any fields in either the Provisioner or AWSNodeTemplate that you think Karpenter should drift nodes on? 

I'm thinking that if Karpenter detected a node using a [subnet](https://karpenter.sh/v0.27.0/concepts/node-templates/#specsubnetselector) or [security group](https://karpenter.sh/v0.27.0/concepts/node-templates/#specsecuritygroupselector) isn't the one resolved from the AWSNodeTemplate selectors, Karpenter should deprovision the node and spin up a new one. I'm thinking the same for node [Requirements](https://karpenter.sh/v0.27.0/concepts/provisioners/#specrequirements), but not sure if we want to deprovision nodes for [tags](https://karpenter.sh/v0.27.0/concepts/node-templates/#spectags) or [labels](https://karpenter.sh/v0.27.0/concepts/provisioners/). Thoughts?

**Comment by sidick** [comment]
I'm using drift detection in production, and I would suggest adding drift detection. Some extra parts to be monitored and would be useful would be kubeletConfiguration and blockDeviceMappings in the node templates.

**Comment by blakepettersson** [comment]
> I would definitely want it to deprovision for tags or labels drift.

I'd settle just for tags, IMO. I'm not sure whether labels drift should deprovision a node, but don't feel too strongly about that.

**Comment by davidnortonjr-sps** [comment]
Deprovisioning based on user-data drift would be helpful.

**Comment by sidewinder12s** [comment]
Having drift selectively deprovision based on a random assortment of fields available on provisioners and/or NodeTemplates seems fraught with issues.

**Comment by njtran** [comment]
@johngmyers @blakepettersson can you share more on your thoughts on tags? And labels?

My thinking is it's hard to know which labels/tags to drift on. Say a user manually adds a label on the node, or a tag on the instance that isn't included in the Provisioner/AWSNodeTemplate specs, then should we drift? Similarly, if we remove a label/tag key-value pair from the requirements, this results in the same situation. Then it's up to Karpenter to figure out how strict this map equality should be to consider drift, which I think is a slippery slope.

**Comment by njtran** [comment]
@sidewinder12s I agree that we shouldn't add things in without thinking, but I see as some fields are inherently more important than others, i.e. `SecurityGroupSelector` and `SubnetSelector` being required in the `AWSNodeTemplate`. I similarly feel the same for node requirements, which often are used to enforce instance types/sizes, zone topology, capacity-type, and architecture requirements for the workloads on the nodes.  

Do you feel the same way?

**Comment by njtran** [comment]
Maybe we could propagate a `node-template-hash` to nodes that hashes the full resolved set of Provisioner and AWSNodeTemplate requirements, and each provisioner maintains that hash to use as a comparison for Drift. Users could manually label/taint their nodes, but not have it drift unless the Provisioner hash changes, which would only happen if a user changes the Provisioner/ProviderRef.

**Comment by johngmyers** [comment]
Our use case for tags is primarily for cost control tracking. A change would be to reclassify a provisioner to charge instances directly rather than on a per-pod basis or to reflect an organizational change.

Our use case for labels is primarily to dedicate a provisioner's nodes to particular teams/workloads, perhaps due to latency or on-node-storage requirements.

In these cases drift is undesirable.

**Comment by johngmyers** [comment]
My view is that if a node could have been created from the current spec then it has not drifted, whereas if it could not have been created it should be deprovisioned (subject to rate limits, etc.)

So if the zone requiremens changed from `["a"]` to `["a", "b"]` then no nodes need be deprovisioned. But if the opposite change is made then all nodes in zone b should be deprovisioned.

**Comment by johngmyers** [comment]
I am saying I want drift to be remediated by karpenter.

**Comment by grandich** [comment]
@ellistarn Regarding "ability to control when and when not to expire nodes":

- (this issue) 8) [#903](https://github.com/aws/karpenter/issues/903) - Provide ability on when to actually rotate expired nodes
- https://github.com/aws/karpenter/pull/1920

Just to understand: Will the proposed way to address this be using Node Disruption Budget and k8s cronjobs updating them to achieve "maintenance windows"?

**Comment by njtran** [comment]
Changed the title and updated this issue to be more accurate of the current state of affairs. Added a design doc on how we're thinking Drift should work for the rest of the known fields here: https://github.com/aws/karpenter-core/pull/366

**Comment by hendryanw** [comment]
Hi, I’ve searched online and in Github, but can’t find the documentation covering the node patch / update. It’s related to #1716, which I saw it has already been ticked. 

Can you please help guide me where can I the documentation?

**Comment by njtran** [comment]
@hendryanw you can drive node patches/updates by deprovisioning. Karpenter does this natively through Drift: https://karpenter.sh/docs/concepts/deprovisioning/#drift

**Comment by calvinbui** [comment]
can we add https://github.com/aws/karpenter/issues/3059 to this list?

**Comment by engedaam** [comment]
Just released v0.30.0-rc.0 which contains the full set of [drift expansion](https://karpenter.sh/preview/concepts/deprovisioning/#drift). Checkout the full release notes in [karpenter](https://github.com/aws/karpenter/releases/tag/v0.30.0-rc.0) and [karpenter-core](https://github.com/aws/karpenter-core/releases/tag/v0.30.0-rc.0)

**Comment by njtran** [comment]
Hey all, I've linked an [RFC here](https://github.com/aws/karpenter-core/pull/516) that has some of the API decisions we're thinking about for some of the linked items in this mega issue. 

- https://github.com/aws/karpenter/issues/1302, https://github.com/aws/karpenter/issues/903  - Maintenance Windows
- https://github.com/aws/karpenter/issues/4529 - Node Disruption Budget
- https://github.com/aws/karpenter/issues/3059 - Per-node TTL for Consolidation

Please take a read and give a review if you can!

**Comment by njtran** [comment]
Considering this is an extremely old issue, and is tracked for a multitude of issues, I'm closing this out as completed, as the issues that we've been planning to fix have been since merged. The remainder of issues that are open should continue to be tracked individually. Thanks!
